### PR TITLE
Include name entry 10 (description)

### PR DESCRIPTION
**Pull request by jamesgk**

### CODE REVIEW

**Comment by jamesgk** [comment]
Ping

**Comment by dougfelt** [comment]
LGTM

Historically, Monotype has used 2-digit minor version numbers while Adobe uses 3-digit ones.  I take it there's nothing in the sources that could make this distinction?  Not that I want to keep it...

**Comment by jamesgk** [comment]
I don't think there is. I'm not sure how the tools will handle that exactly, but hopefully it won't really make a difference. Unless there's some reason we want to keep them in sync or something.

**Comment by dougfelt** [comment]
Main issue, is that this is in sync with the fontRevision in the head table, and that is a fixed point number.  Version 1.001 and version 1.01 are not the same.  Since we routinely 'bump' the 'minor' version we need to define the number of decimals we are using.  And since we're following on from the existing fonts with two-digit minor numbers we need to figure out what this requires for the new versions-- does 1.04 turn into 1.041?  1.005?

**Comment by jamesgk** [comment]
Oh yea, good question. Well I'd say it's best to treat major / minor versions as effectively two separate integers, so 1.04 -> 1.005. Someone else may have different ideas though.

**Comment by dougfelt** [comment]
Yeah. This works ok until we go from 1.01 to 1.002 and keep revising to
1.009 to... what?  We can reuse the head revision number at that point, I
guess, and rely on the fact that the version strings look different.

**Comment by jamesgk** [comment]
Right. I wouldn't think it would be a big issue, though my experience with this stuff is rather limited.

**Comment by behdad** [comment]
Ignore CJK numbering and continue 2-digit?  I don't know how far of a practical problem reaching 1.99 is...

**Comment by jamesgk** [comment]
That might require special handling in various places. I'm not sure how widespread the 3-digit assumption is made, but it's present here from ufo2fdk.

**Pull request merged**
