### PR TITLE
[markWriter] Add MarkAttachmentType flags to mkmk

### PR DESCRIPTION
**Pull request by jamesgk**
Should resolve https://github.com/googlei18n/ufo2ft/issues/52, for now.
r? @khaledhosny

### CODE REVIEW

**Comment by khaledhosny** [comment]
This does not seem to work, the `mkmk` feature is not applied at all now. I think this is because the mark class does not include the base marks.

**Comment by jamesgk** [comment]
Hmm :frowning: it seems to be working fine with Noto. I tried building Mada but got an assertion error from feaLib. Not sure how to debug this.

**Comment by anthrotype** [comment]
try updating the fonttools requirement to the latest HEAD. Behdad fixed something with Extension subtables overflowing.

**Comment by khaledhosny** [comment]
Here is a UFO that should be buildable with fontmake: [Mada-Medium.ufo.zip](https://github.com/googlei18n/ufo2ft/files/384572/Mada-Medium.ufo.zip)

Testing the string `بَ بَّ نَّ بِّ بِ نَ` with font generated by my code, I get:
good

But with ufo2ft I get:
bad

**Comment by jamesgk** [comment]
That's a helpful test string, thanks. I'm still not convinced this is a ufo2ft bug though, because I'm getting correct results (AFAICT) from [NotoSansArabic-Regular.ufo.zip](https://github.com/googlei18n/ufo2ft/files/384618/NotoSansArabic-Regular.ufo.zip). I guess this will take more debugging.

**Comment by jamesgk** [comment]
What surprises me actually is that this example string doesn't render correctly from the output *without* this PR. I only see an issue with `بِّ`, because the bottom-most mark is attaching to the base glyph rather than the dot below. But why would that be, if a mark attachment is defined on the dot below and that's the closest preceding character? I don't understand this aspect of GPOS.

Anyways, I guess this PR is unsuitable after all for resolving your case. So let's revisit the idea using group prefixes, maybe defining something as a class attribute similar to what we do with the kern feature writer.

**Comment by khaledhosny** [comment]
I’m checking Noto Sans Arabic to see what is the difference and if I can get my font to work the same way.

**Comment by khaledhosny** [comment]
Oh, it seems that Noto Sans Arabic is not using the mkmk anchors at all, but instead ligates the marks:
```
$ hb-shape NotoSansArabic-Regular.ttf "بِّ" --no-positions --cluster-level=1
[shadda_kasra.ar=1|beh.ar=0]
```

For comparison, in Mada this gives:
````
$ hb-shape Mada-Regular.ttf "بِّ" --no-positions --cluster-level=1
[uni0650=2|uni0651=1|ar1Dot.below=0|arBeh.isol=0]
````

**Comment by jamesgk** [comment]
Yea, I noticed that as well. It was strange to me that uni0650 was attaching to arBeh.isol rather than ar1Dot.below.

**Comment by khaledhosny** [comment]
That is because the MarkAttachmentType class does not include ar1Dot.below (since it is a base mark) but only uni0650 and uni0651 etc., so the mkmk lookup ends up not being applied at all and the regular mark lookup is applied instead.

If we want to continue with the current approach, then we will need to add the base marks to the class used in MarkAttachmentType.

**Comment by jamesgk** [comment]
I'm talking about the output without this PR, without using the MarkAttachmentType flag. ufo2ft on master generates this feature source:

```
markClass uni0650 <anchor 0 0> @MC_markBelow;
...
markClass uni0650 <anchor 0 0> @MC_markBelowDot;
...
feature mark {
  ...
  lookup mark9 {
    ...
    pos base arBeh.isol <anchor 402 -139> mark @MC_markBelow;
    ...
  } mark9;
} mark;

feature mkmk {
  ...
  lookup mkmk10 {
    pos mark ar1Dot.below <anchor 0 -140> mark @MC_markBelowDot;
    ...
  } mkmk10;
} mkmk;
```

Why would the mark rule take precedence over the mkmk rule for this string? I'd expect the opposite since ar1Dot.below is closer to uni0650.

**Comment by khaledhosny** [comment]
Because the mkmk lookup will stop at the first mark glyph, so it will stop at uni0651, check if the lookup has an anchor to apply between it and uni0650 (there is none) and stops there. That is where the MarkAttachmentType flag is needed, it should tell the lookups to ignore any glyphs other than uni0650 and ar1Dot.below, so the lookup will skip uni0651 and stop at ar1Dot.below, finds the anchor and applies it.

**Comment by jamesgk** [comment]
OK that makes sense. But I still feel like this should be automate-able somehow. I guess I still don't get what should go into the class for the MarkAttachmentType flag -- would it work to include the glyphs used as bases in the lookup, in addition to the glyphs used as marks?

**Comment by khaledhosny** [comment]
Yes, I think this should work.

**Comment by jamesgk** [comment]
It does work, but only with UseMarkFilteringSet since there are commonly base glyphs shared between lookups. But actually, I just tried to compile the output feature syntax with makeotf, and it worked! So maybe that's a good solution?

**Comment by jamesgk** [comment]
PTAL

**Comment by khaledhosny** [comment]
LGTM

**Comment by jamesgk** [comment]
Thanks so much for your patience! Let me know if this is still insufficient in any way.

**Pull request merged**
