### PR TITLE
Simple regression tests for public.glyphOrder and production names

### PR DESCRIPTION
**Pull request by verbosus**
Which ufo2ft currently doesn’t have.

### CODE REVIEW

**Comment by verbosus** [comment]
I signed it.

**Comment by anthrotype** [comment]
Hey Antonio, thanks for contributing here!
The tests look good to me, however I'd prefer that the tests folder keeps the same layout as the Lib/ufo2ft folder, so I'd organise the test modules to match the modules of the ufo2ft package, one test module each.
Do you mind doing that?

**Comment by anthrotype** [comment]
Thanks.
Also, can you please wrap unittest.main calls with sys.exit()?
Even though we don't call the test modules directly as we use pytest to discover them, it's good practice to have it there, in case someone does run the test modules as scripts. The failing exit code is then returned properly to the shell.

**Comment by anthrotype** [comment]
I see the other test modules are missing the sys.exit in main.
Well, it's no big deal. We can add them later, or even better completely remove the `if __name__ is "___main__"`, since one should use pytest to run the test modules anyway.

**Comment by anthrotype** [comment]
It would be nice to also have another small test for when the public.glyphOrder is specified in the lib.plist.

**Comment by anthrotype** [comment]
Oops, sorry, of course I meant the public.postscriptNames! :)

**Comment by verbosus** [comment]
See googlei18n/ufo2ft#103

**Pull request merged**
