### PR TITLE
WIP: Use AGLFN names when converting glyph names to production names

### PR DESCRIPTION
**Pull request by madig**
Previously, without a public.postscriptNames dictionary within the UFO, ufo2ft would convert _all_ glyph names into uniXXXX or uXXXXXX form.

This code tries to instead use AGLFN names for glyphs listed therein.

I tested it with this font: [Test_Lt.zip](https://github.com/googlei18n/ufo2ft/files/1671460/Test_Lt.zip). It has the following glyphs with their Unicode values, if any:
```
[('ie.smcp', 1077),
 ('.notdef', None),
 ('n_ie', None),
 ('n', 110),
 ('f_f_l', None),
 ('ie', 1077),
 ('.null', 0),
 ('ie_ie', None),
 ('someemoji', 128516),
 ('test', None),
 ('ie.case', None)]
```
The code produces this:
```
    <GlyphID id="0" name=".notdef"/>
    <GlyphID id="1" name="uni0000"/>
    <GlyphID id="2" name="n"/>
    <GlyphID id="3" name="uni0435"/>
    <GlyphID id="4" name="n_uni0435"/>
    <GlyphID id="5" name="uni0435.case"/>
    <GlyphID id="6" name="test"/>
    <GlyphID id="7" name="u1F604"/>
    <GlyphID id="8" name="uni0435.smcp"/>
    <GlyphID id="9" name="uni04350435"/>
    <GlyphID id="10" name="f_f_l"/>
```
Is the code missing any important logic? Modified tests will follow later.

### CODE REVIEW

**Comment by madig** [comment]
The following code is related, it generates a public.postscriptNames dictionary for all glyphs whose names don't already match the AGLFN name:
```Python
def rename(ufo, n):
  if n == ".notdef":
    return n
  if n == ".null":
    return "uni0000"
  name = n.split(".", 1)[0]
  if "_" in name:
    return "_".join([rename(ufo, n) for n in name.split("_")])
  uni = ufo[name].unicode
  if uni is None:
    return n
  else:
    if name in fontTools.agl.AGL2UV:
      return n
    else:
      u = '%s%04X' % ('u' if uni > 0xffff else 'uni', uni)
      return n.replace(name, u)


def ps_name_dict(ufo):
  postScriptNames = {}
  for glyph in ufo:
    r = rename(ufo, glyph.name)
    if r != glyph.name:
      postScriptNames[glyph.name] = r
  return postScriptNames
```

**Comment by madig** [comment]
Maybe this is more cosmetic than useful? Close?

**Comment by anthrotype** [comment]
Indeed. If one really cares, one can add a `public.postscriptNames` to the UFO lib.

**Comment by anthrotype** [comment]
Following discussion at https://github.com/googlei18n/fontmake/issues/465, I changed the ufo2ft postProcessor so that, by defaut, it will not rename glyphs if the public.postcriptNames is missing. To apply the uniXXXX renaming from the glyph's unicodes (in absence of an explicit public.postcriptNames mapping) one now needs to explicitly request it. 
That means, either setting `com.github.googlei18n.ufo2ft.useProductionNames` to True in the UFO.lib, or calling compile functions with `useProductionNames=True` (that's what fontmake does when called with --production-names command line option).

**Pull request closed without merging**
