### PR TITLE
Fontinfo fixes

### PR DESCRIPTION
**Pull request by jamesgk**
I hope these are uncontroversial. Goal is to resolve https://github.com/googlei18n/ufo2ft/issues/76 and resolve https://github.com/googlei18n/ufo2ft/issues/78.

### CODE REVIEW

**Comment by dougfelt** [comment]
Travis test is failing, is this a likely cause?

**Comment by jamesgk** [comment]
Definitely. Let me fix this up and I'll update the thread when ready.

**Comment by jamesgk** [comment]
Huh, maybe we shoud use this method: https://github.com/googlei18n/glyphsLib/issues/78#issuecomment-257739083 instead...

**Comment by anthrotype** [comment]
yeah, I think Georg's formulas work better as fallback values than the ones from this PR.

**Pull request merged**
