### PR TITLE
Minor things

### PR DESCRIPTION
**Pull request by jamesgk**
@adrientetar would you like to confirm that this won't break anything?

### CODE REVIEW

**Comment by anthrotype** [comment]
LGTM, with a few suggestions:

1) The setup.py still prints a warning if robofab is not installed. Maybe we should change that with ufoLib?

2) In the UFO3 branch of defcon, the font object has a `glyphOrder` property. This could be used when the `glyphOrder=None` argument in the `OutlineCompiler` constructor is not specified by the user. What happens now is that the glyphs are sorted alphabetically (with the exception of the .notdef and the space glyph), unless the user passes an explicit ordering. So if one wishes to keep the font's original glyph order, one needs to explicitly pass `font.glyphOrder` as the second argument. However this seems a bit redundant to me, since I'm already passing the font instance as the first argument. I think it should be implicit that if I don't pass a `glyphOrder` argument, I mean to keep the order which is already in the font (of course, `if hasattr(font, 'glyphOrder')`, instead of reordering the glyphs alphabetically.

3) about the position of the space glyph; @kenlunde suggested in OpenType list to change the spec's "First Four Glyphs" recommendations (inherited from the TrueType spec) to only recommend that glyph ID 1 be a glyph with no contours and non-zero advance width and be mapped to U+0020. However his proposal hasn't made it to the spec yet. So I think it's fine for now to just ensure that GID 0 is the ".notdef" glyph (used to fill in gaps for some cmap subtable formats), and don't force the space glyph to be at glyph index 1.

**Comment by adrientetar** [comment]
I think glyphOrder could be amended to only compile glyphs it contains, so it can be used to compile only a subset of the glyphs.

**Comment by anthrotype** [comment]
sure, but it should also be used as the predefined glyph ordering.

**Comment by jamesgk** [comment]
Thanks, how does this look?

**Comment by anthrotype** [comment]
:+1:

**Pull request merged**
