### PR TITLE
Travis, tox, pytest, etc.

### PR DESCRIPTION
**Pull request by anthrotype**
I added a minimal `.travis.yml` and `tox.ini` to run py.test script on Python 2.7 and 3.5. This should be enough to get us started on writing the test suite.

I used this nice package that makes configuring Travis for tox much easier:
https://github.com/ryanhiebert/tox-travis

### CODE REVIEW

**Comment by jamesgk** [comment]
Travis should now be active for this repo, could you push another commit to test that it works?

**Comment by anthrotype** [comment]
Well, it does work on my work, so it will defbtely work here too. I don't know what to modify..

**Comment by adrientetar** [comment]
I think James means pushing again so Travis builds this PR, git commit --amend should rehash.

**Comment by anthrotype** [comment]
ok done. I'm off -- it's 10pm over here.
cheers!

**Comment by jamesgk** [comment]
Thanks!

**Pull request merged**
