### PR TITLE
Update featureCompiler to use glyphNames instead of glyphMap

### PR DESCRIPTION
**Pull request by madig**
... for instantiating feaLib.parser.Parser().

Is this the correct fix? If so, tests to follow.

### CODE REVIEW

**Comment by anthrotype** [comment]
No. it's already working as it should. ufo2ft is passing a dictionary as the second positional argument to `feaLib.parser.Parser`, i.e. called `glyphNames`; the dict keys are collected into a set by the Parser constructor.
You only get the warning if you pass the old keyword argument `glyphMap`, but ufo2ft is no longer doing that.

Anyway, i'm changing lots of things in a private branch which I haven't pushed yet. Stay posted. Thanks anyway.

Ah, about the CLA, you should tell Denis or Bianca to add your new DaMa email address to the internal GoogleGroup mailing list of contributors to Google's repositories.

**Comment by madig** [comment]
It is still passing in glyphMap (https://github.com/googlei18n/ufo2ft/blob/master/Lib/ufo2ft/featureCompiler.py#L107) unless I'm missing something :confused:

**Comment by anthrotype** [comment]
But it’s passed as a positional argument, so it is assigned to glyphNames, the second parameter.
The warning is issued only if you pass be deprecated keyword argument, which was renamed. Try.

**Comment by anthrotype** [comment]
As I said I have already chanced this block if code in my local branch, please just ignore it for now

**Comment by sladen** [comment]
@anthrotype: would it be worth pushing that here (then it would be clearer what the preferred fix is).

**Comment by anthrotype** [comment]
I’ll do when I’m ready to. I don’t see why you’re so concerned by that small deprecation message This is a non issue.

**Comment by anthrotype** [comment]
Also because, there isn’t any deprecation message, as Inalteady explained.

**Comment by sladen** [comment]
@anthrotype: at the moment one contributor has offered a patch;  another contributor has said that this patch is wrong, and that there is a better patch, but it is secret.  This leaves that first contributor stuck, and prevents anyone from learning from the intended solution is.  This is with all those involved being at least *vaguely* familiar with the source code—so an actual end user without any context is likely going to be completely confused.

The commit that introduced the warning, at:
* fonttools/fonttools/commit/0ff6be5ff89ec1e24469fa1171eac2f669bf60b8

also exchanged `getReverseGlyphMap()` for `getGlyphOrder()`, which was something that was also being suggested here.

**Comment by anthrotype** [comment]
I’m not simply “another contributor”, but the current maintainer. And I have explained that there was no issue (as Nikolaus just confirmed), and therefore no solution to be discussing upon.
What I’m working is no “secret”, I’ll just push when I feel ready to submit for review.

**Pull request closed without merging**
