### PR TITLE
Add fallback for hhea caretSlopeRise and caretSlopeRun to match makeotf

### PR DESCRIPTION
**Pull request by punchcutter**
From https://github.com/googlei18n/glyphsLib/pull/284, but do it here instead because we want to match what makeotf does, not Glyphs itself.

### CODE REVIEW

**Comment by anthrotype** [comment]
thanks!

**Comment by anthrotype** [comment]
@punchcutter I made a few small adjustments like using build-in round and supporting the case where only one of the two is defined; I hope you don't mind
https://github.com/googlei18n/ufo2ft/blob/2d42d89b41538acdd89e66faa6c7c475bbea52ff/Lib/ufo2ft/fontInfoData.py#L76-L103

**Comment by punchcutter** [comment]
@anthrotype I started to add non 1000 options for caretSlopeRise because the hhea spec doesn't care, but makeotf appears to always set it to 1000. It seems odd that anyone would ever manually set only the run or the rise, but this looks good to cover it all. Thanks!

**Comment by anthrotype** [comment]
it is odd, and I thought about warning and ignore if one of the two was missing.. but then I thought I could just make it work.

**Comment by punchcutter** [comment]
makeotf has no option to set those manually since they are always calculated from the italic angle, but more control doesn't hurt.

**Pull request merged**
