### PR TITLE
Use "*_1" anchors when creating mark GPOS feature

### PR DESCRIPTION
**Pull request by jamesgk**
Part of https://github.com/googlei18n/glyphs2ufo/issues/33

### CODE REVIEW

**Comment by adrientetar** [comment]
This looks like it belongs to glyphs2ufo, not the UFO toolchain. I mean why should a Glyphs convention of using anchors be baked in here?

**Comment by jamesgk** [comment]
It already was, really. I just wasn't aware of the additional _1/_2/... anchor names. But yea I'm not sure what the best default behavior would be here, or whether this anchor naming pattern is generally used outside of Glyphs.

Is there a standard anchor naming pattern that can be output by glyphs2ufo, and used by default here? Otherwise, I'm hesitant to change the anchor output of glyphs2ufo arbitrarily. Alternatively, we can output anchors in glyphs2ufo as they are in Glyphs source, and require any client using glyphs2ufo and ufo2ft (e.g. fontmake) to define the behavior in this PR for generating mark features from those anchors.

**Comment by adrientetar** [comment]
> But yea I'm not sure what the best default behavior would be here, or whether this anchor naming pattern is generally used outside of Glyphs.

Well, the only convention I'm avare of is e.g. "top" on the base glyph and "_top" on the diacritic.

By the way, why do you mean by this "attach components" (top_2) thing? Is it used to make component glyph out of a few components? I'm not sure I understand its purpose.

**Comment by jamesgk** [comment]
> Well, the only convention I'm avare of is e.g. "top" on the base glyph and "_top" on the diacritic.

OK, if that's a general convention then I'm fine with having glyphs2ufo output conform to it.

> By the way, why do you mean by this "attach components" (top_2) thing? Is it used to make component glyph out of a few components? I'm not sure I understand its purpose.

Anchors are used in Glyphs to attach marks as glyph components (see here https://glyphsapp.com/tutorials/diacritics under "Components" and here https://glyphsapp.com/tutorials/advanced-diacritics-multiple-anchors for top_2-related stuff specifically).

**Comment by adrientetar** [comment]
> https://glyphsapp.com/tutorials/advanced-diacritics-multiple-anchors for top_2-related stuff specifically

That's interesting. I don't think there is record of this in UFO. cc @moyogo

**Comment by jamesgk** [comment]
> I don't think there is record of this in UFO.

I definitely didn't see anything like that in the UFO spec. So I figure we should just use some existing convention for the default behavior here.

**Comment by graphicore** [comment]
> I don't think there is record of this in UFO.

This is part of what I tried to complain about missing in UFO at the fonts-bof at the LGM on Monday.

Another missing thing is IMO the means to create the Mark-to-Ligature feature with the data present in UFO.

**Comment by adrientetar** [comment]
> This is part of what I tried to complain about missing in UFO at the fonts-bof at the LGM on Monday.

Right, we should make a wishlist document on GDoc or so. cc @frank-trampe

**Comment by moyogo** [comment]
As far as I'm aware the underscore extension in anchor name is Glyphs.app specific but it’s a good model.
This kind of logic should be in a mkmkFeatureWriter.

The FeatureWriter model should probably be extended to any feature, with a default logic for kern, mark and mkmk that users could change by passing custom featureWriters when calling compileOTF() like with the kernFeatureWriter or markFeatureWriter.

**Comment by graphicore** [comment]
> Right, we should make a wishlist document on GDoc or so

This was the designated doc: https://etherpad.openstack.org/p/UFO_GDEF_Support

**Comment by schriftgestalt** [comment]
The _1/2/3 anchors are usually in ligatures and are used to generate the liga2mark feature. There should be caret_1/2/3 anchors, too. That are used to generate the caret position part in the GDEF table.

**Comment by jamesgk** [comment]
OK, I'm now thinking that we should use the Glyphs model here for mark-to-ligature attachment. Specifically, use _1/2/3 anchors in a separate lookup of the mark feature which contains `pos ligature` statements.

**Comment by behdad** [comment]
Sgtm.

On Thu, Apr 21, 2016 at 3:55 PM, James Godfrey-Kittle <
notifications@github.com> wrote:

> OK, I'm now thinking that we should use the Glyphs model here for
> mark-to-ligature attachment. Specifically, use _1/2/3 anchors in a separate
> lookup of the mark feature which contains pos ligature statements.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/ufo2ft/pull/34#issuecomment-213150821>
>



-- 
behdad
http://behdad.org/

**Pull request closed without merging**
