### PR TITLE
support compiling sparse masters by layerName

### PR DESCRIPTION
**Pull request by anthrotype**
continuation of #295

### CODE REVIEW

**Comment by anthrotype** [comment]
@madig to appease the CLA bot, you just need to say "I'm OK with blah blah"

**Comment by anthrotype** [comment]
how about we optionally accept tuples of (font, layerName) in `compileInterpolatableTTFs`

```
compileInterpolatableTTFs([font1, (font1, "Medium"), font2])
```

instead of the current way of having to list all the `None` items (for default layer) in a separate `layerNames` parameter?

```
compileInterpolatableTTFs([font1, font1, font2], layerNames=[None, "Medium", None])?
```

**Comment by anthrotype** [comment]
alternatively, we could change the `compileInterpolatableTTFs` function to accept a DesignSpaceDocument in addition (and in alternative to) a list of fonts.
If we do that, then the `layerNames` parameter would be unnecessary/redundant, as ufo2ft would simply collect all the SourceDescriptors from the designspace and access their `font` and `layerName` attributes.

**Comment by madig** [comment]
Me and Denis think that passing a Designspace file might be a good idea. The function should however be written to look at a SourceDescriptor.font attribute before loading the source, to make in-memory pre-processing possible.

**Comment by madig** [comment]
I'm OK with blah blah.

**Pull request merged**
