### PR TITLE
Support remove overlaps and custom filters

### PR DESCRIPTION
**Pull request by anthrotype**
Towards addressing https://github.com/googlei18n/ufo2ft/issues/120

Composite glyph decomposition, overlap removal (via booleanOperations) and cubic to quadratic conversion are now handled as "filters" in the same way as custom user-defined filters.

Fixes https://github.com/googlei18n/ufo2ft/issues/166

Please read commit messages for more info.

It'd be nice if those who use or have used ufo2ft directly, without fontmake, could take a look.
Thanks

### CODE REVIEW

**Comment by anthrotype** [comment]
I'm planning on adding some tests in the coming days.

**Comment by anthrotype** [comment]
this PR also adds support for coverage and codecov

https://codecov.io/gh/googlei18n/ufo2ft

**Comment by anthrotype** [comment]
I *think* the annoying codecov PR messages will stop once the `.codecov.yml` file is merged into master, along with this PR.

**Comment by anthrotype** [comment]
I going ahead and merge this. I'll wait a few days before cutting a release in case any issues arise.
(I hope codecov.io finally shut up)

**Comment by behdad** [comment]
💯

**Pull request merged**
